name: Slack Notification Demo
on:
  push:
    branches: [master]
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_COLOR: '#3278BD'
        SLACK_ICON: ':bell:'
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_TITLE: Title
        SLACK_USERNAME: rtCamp
        SLACK_MESSAGE: '{"text": "Sup! We're hacking shit together @HackSussex :spaghetti:"}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DEVOPS }}
